name: Notify Slack

on:
  push:

  workflow_dispatch:

jobs:
  notify_slack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: notify-slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "key": "value",
              "foo": "bar"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

