name: Slack通知

on:
  push:

  workflow_dispatch:

jobs:
  slack-notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: notify-slack
        uses: slackapi/slack-github-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: '#actions-bot'
          text: "ワークフロー '${{ github.workflow }}' が完了しました。"
          color: '#0000FF'
