name: Notify Slack

on:
  push:

  workflow_dispatch:

jobs:
  notify_slack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: notify-slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          slack-message: "Pushed GitHub Repository."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
